dist: xenial
os: linux
language: node_js
node_js:
- '14'
script:
- npm run build
before_deploy:
  - cd dist && zip -r halversondm.zip .
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: ${AWS_ACCESS_KEY_ID}
  secret_access_key:
    secure: ${AWS_SECRET_ACCESS_KEY}
  region: "us-east-1"
  app: "web"
  env: "web-env"
  bucket_name: "elasticbeanstalk-us-east-1-442620099008"
  zip_file: dist/halversondm.zip
  skip_cleanup: true
notifications:
  slack:
    secure: knkecPsTXNRHe1iDl8tgWcZEu/hbjJSkKvpvW/z7pVQ4rZk4D0HnSLkchQAYkg3ElRVH4AV5ZiewrzJqZp1BSRVjBIXAfOKvAkuI8QQd3Vs0ebBqEZJtVqB0pMSDep2mWv3LbVkQuIjMm7yVL5saQ0rZm2BIaFlM417Qs0RRMvz4kET1DZms89LTwc90tWWE3yPzBsGWkLy9rndgymrXCw9moVfq6vS8+fyThZTzYqM9CloZEyRApN3iq9mN+fg5xXvxKoT2eoFp3z1D7mxYFEGM8+vqmW+YnxMQtONTZAnl6aBxeHCXNWZ+Wj4OoxJFHcXvvDfbWvobBdTh7RWkF2gKQtClaS0zZa0LLHBmJy1bj10cbvPlL0dQQNamxofHCp5Oc/HrgMYvGtrqMKGFrFtJ/NvIvzn+OOaP8d+q+AixTAItVrYNqZOGWEIiUG+iRJ1dwikSMrlYPGhzRrO1R3ldgcEijoWdZcKpb3BUzadNBfhGgkOKVqdBDAMFOeSnu3yBGw7hzQNUz9NZrSg6P1ESDPqfiqPodHm784wMwk9hiYZgJFAUTCWHhLt9BvQSJpP+p8RHW6Xd7rSSAP3X+i07K3lgrqkFDZCNSRvbMkri3cXUnXxCq1wHJcHMisfRibS9gqSkxXdopDuWISTMXHc5v1Iy8VDiySQtNjWCO4s=
