apiVersion: v1
kind: Pod
metadata:
  labels:
    run: halversondm
  name: halversondm
spec:
  containers:
  - image: halversondm:latest
    name: halversondm
    resources: {}
    ports:
      - containerPort: 3000
    imagePullPolicy: Never
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: halversondm
  name: halversondm
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    run: halversondm
  type: ClusterIP
