name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Build Code
        run: npm run build
      - name: Compress dist
        if: ${{ success() }}
        run: cd dist && zip -r halversondm.zip .
      - name: Deploy to EB
        if: ${{ success() }}
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: web
          environment_name: web-env
          version_label: ${{github.run_number}}
          region: us-east-1
          deployment_package: dist/halversondm.zip
          existing_bucket_name: elasticbeanstalk-us-east-1-442620099008
