name: CI and CD
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: arm64-ubuntu-24-2c

    env:
      ECR_REPOSITORY: halversondm/halversondm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm ci

      - name: Build Code
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names "${{ env.ECR_REPOSITORY }}" || \
            aws ecr create-repository --repository-name "${{ env.ECR_REPOSITORY }}"

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd dist
          docker buildx build --platform linux/arm64 -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Tell the ECS Service to update with the latest image
        run: |
          aws ecs update-service \
            --cluster fluffy-zebra-nlfv4i \
            --service halversondm-service-1ch1gwik \
            --force-new-deployment